"""Add products table

Revision ID: c42e0b7c7aac
Revises: f8b216e1b663
Create Date: 2025-12-09 08:04:38.213398+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c42e0b7c7aac'
down_revision: Union[str, None] = 'f8b216e1b663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_recommendations_id', table_name='product_recommendations')
    op.drop_index('ix_product_recommendations_product_id', table_name='product_recommendations')
    op.drop_index('ix_product_recommendations_user_biomarker_id', table_name='product_recommendations')
    op.drop_table('product_recommendations')
    
    # Removed dropping of health_reminders
    
    op.add_column('products', sa.Column('composition', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('composition_table', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('sale_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('filter_stocks', sa.String(), nullable=True))
    op.add_column('products', sa.Column('value', sa.String(), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_index('ix_products_slug', table_name='products')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    
    # First drop foreign key constraint
    try:
        op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    except Exception:
        pass
        
    op.drop_column('products', 'rating')
    op.drop_column('products', 'old_price')
    op.drop_column('products', 'health_benefits')
    op.drop_column('products', 'active_ingredients')
    op.drop_column('products', 'stock_quantity')
    op.drop_column('products', 'is_featured')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'currency')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'target_biomarkers')
    op.drop_column('products', 'in_stock')
    
    # Drop category_id column
    op.drop_column('products', 'category_id')
    
    # NOW we can safely drop product_categories table
    op.drop_index('ix_product_categories_id', table_name='product_categories')
    op.drop_index('ix_product_categories_slug', table_name='product_categories')
    op.drop_table('product_categories')

    op.drop_column('products', 'image_url')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'slug')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'short_description')
    op.drop_column('products', 'images')
    op.drop_column('products', 'reviews_count')
    op.drop_column('products', 'external_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skipping exact downgrade logic for simplicity as we moved forward with new schema
    pass
