"""Add medical_documents table for medcard

Revision ID: f8b216e1b663
Revises: 
Create Date: 2025-12-07 10:19:20.134040+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8b216e1b663"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "biomarkers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "code",
            sa.String(length=50),
            nullable=False,
            comment="Unique code (e.g., HGB, FE, TSH)",
        ),
        sa.Column(
            "name_ru", sa.String(length=255), nullable=False, comment="Russian name"
        ),
        sa.Column(
            "name_en", sa.String(length=255), nullable=True, comment="English name"
        ),
        sa.Column(
            "aliases",
            sa.Text(),
            nullable=True,
            comment="Comma-separated aliases (HGB,Hb,Гемоглобин,Hemoglobin)",
        ),
        sa.Column(
            "category",
            sa.Enum(
                "HEMATOLOGY",
                "BIOCHEMISTRY",
                "HORMONES",
                "VITAMINS",
                "MINERALS",
                "LIPIDS",
                "LIVER",
                "KIDNEY",
                "THYROID",
                "INFLAMMATION",
                "OTHER",
                name="biomarkercategory",
            ),
            nullable=False,
        ),
        sa.Column(
            "default_unit",
            sa.String(length=50),
            nullable=False,
            comment="Default measurement unit",
        ),
        sa.Column(
            "alternative_units",
            sa.String(length=255),
            nullable=True,
            comment="Comma-separated alternative units with conversion factors",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="What this biomarker indicates",
        ),
        sa.Column(
            "low_recommendations",
            sa.Text(),
            nullable=True,
            comment="Recommendations when value is low",
        ),
        sa.Column(
            "high_recommendations",
            sa.Text(),
            nullable=True,
            comment="Recommendations when value is high",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_biomarkers_code"), "biomarkers", ["code"], unique=True)
    op.create_index(op.f("ix_biomarkers_id"), "biomarkers", ["id"], unique=False)
    op.create_table(
        "product_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "icon", sa.String(length=100), nullable=True, comment="Icon name or emoji"
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_product_categories_id"), "product_categories", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_product_categories_slug"), "product_categories", ["slug"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("birth_date", sa.DateTime(), nullable=True),
        sa.Column(
            "gender", sa.Enum("MALE", "FEMALE", "OTHER", name="gender"), nullable=True
        ),
        sa.Column(
            "external_user_id",
            sa.String(length=255),
            nullable=True,
            comment="ID пользователя во внешней системе заказчика",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_external_user_id"), "users", ["external_user_id"], unique=False
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "title",
            sa.String(length=255),
            nullable=False,
            comment="User-friendly title",
        ),
        sa.Column(
            "analysis_type",
            sa.Enum(
                "BLOOD_GENERAL",
                "BLOOD_BIOCHEMISTRY",
                "HORMONES",
                "VITAMINS",
                "URINE",
                "OTHER",
                name="analysistype",
            ),
            nullable=False,
        ),
        sa.Column(
            "lab_provider",
            sa.Enum(
                "INVITRO",
                "KDL",
                "GEMOTEST",
                "HELIX",
                "CMD",
                "OTHER",
                name="labprovider",
            ),
            nullable=True,
        ),
        sa.Column(
            "lab_name",
            sa.String(length=255),
            nullable=True,
            comment="Custom lab name if not in enum",
        ),
        sa.Column(
            "analysis_date",
            sa.DateTime(),
            nullable=True,
            comment="Date when analysis was taken",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "MANUAL_REVIEW",
                name="analysisstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "error_message",
            sa.Text(),
            nullable=True,
            comment="Error details if processing failed",
        ),
        sa.Column("raw_text", sa.Text(), nullable=True, comment="Raw OCR text output"),
        sa.Column(
            "ai_summary",
            sa.Text(),
            nullable=True,
            comment="AI-generated summary of results",
        ),
        sa.Column(
            "ai_recommendations",
            sa.JSON(),
            nullable=True,
            comment="AI-generated recommendations",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_analyses_id"), "analyses", ["id"], unique=False)
    op.create_index(op.f("ix_analyses_user_id"), "analyses", ["user_id"], unique=False)
    op.create_table(
        "biomarker_references",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("biomarker_id", sa.Integer(), nullable=False),
        sa.Column(
            "gender",
            sa.String(length=10),
            nullable=True,
            comment="male/female or null for both",
        ),
        sa.Column("age_min", sa.Integer(), nullable=True),
        sa.Column("age_max", sa.Integer(), nullable=True),
        sa.Column("ref_min", sa.Float(), nullable=True),
        sa.Column("ref_max", sa.Float(), nullable=True),
        sa.Column(
            "optimal_min",
            sa.Float(),
            nullable=True,
            comment="Optimal range lower bound",
        ),
        sa.Column(
            "optimal_max",
            sa.Float(),
            nullable=True,
            comment="Optimal range upper bound",
        ),
        sa.Column("critical_low", sa.Float(), nullable=True),
        sa.Column("critical_high", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["biomarker_id"], ["biomarkers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "biomarker_id",
            "gender",
            "age_min",
            "age_max",
            "unit",
            name="uq_biomarker_reference",
        ),
    )
    op.create_index(
        op.f("ix_biomarker_references_biomarker_id"),
        "biomarker_references",
        ["biomarker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_biomarker_references_id"), "biomarker_references", ["id"], unique=False
    )
    op.create_table(
        "health_reminders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "reminder_type",
            sa.Enum(
                "CHECKUP",
                "ANALYSIS",
                "SUPPLEMENT",
                "MEDICATION",
                "APPOINTMENT",
                "CUSTOM",
                name="remindertype",
            ),
            nullable=False,
        ),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("scheduled_time", sa.Time(), nullable=True),
        sa.Column(
            "frequency",
            sa.Enum(
                "ONCE",
                "DAILY",
                "WEEKLY",
                "MONTHLY",
                "QUARTERLY",
                "BIANNUALLY",
                "ANNUALLY",
                name="reminderfrequency",
            ),
            nullable=False,
        ),
        sa.Column("repeat_until", sa.Date(), nullable=True),
        sa.Column("last_triggered", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_occurrence", sa.Date(), nullable=True),
        sa.Column(
            "notify_days_before",
            sa.Integer(),
            nullable=False,
            comment="Send notification X days before",
        ),
        sa.Column("notify_on_day", sa.Boolean(), nullable=False),
        sa.Column("notification_sent", sa.Boolean(), nullable=False),
        sa.Column(
            "related_biomarkers",
            sa.String(length=500),
            nullable=True,
            comment="Comma-separated biomarker codes to check",
        ),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "external_calendar_id",
            sa.String(length=255),
            nullable=True,
            comment="ID in external calendar (Google, Apple)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_reminders_id"), "health_reminders", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_health_reminders_next_occurrence"),
        "health_reminders",
        ["next_occurrence"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_reminders_scheduled_date"),
        "health_reminders",
        ["scheduled_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_reminders_user_id"),
        "health_reminders",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "medical_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "ANALYSIS",
                "CONSULTATION",
                "EXAMINATION",
                "OTHER",
                name="documentcategory",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", sa.String(length=500), nullable=True),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("visit_date", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medical_documents_id"), "medical_documents", ["id"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("short_description", sa.String(length=500), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("old_price", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("images", sa.JSON(), nullable=True),
        sa.Column("in_stock", sa.Boolean(), nullable=False),
        sa.Column("stock_quantity", sa.Integer(), nullable=True),
        sa.Column(
            "external_id",
            sa.String(length=100),
            nullable=True,
            comment="ID в каталоге заказчика",
        ),
        sa.Column(
            "external_url",
            sa.String(length=500),
            nullable=True,
            comment="Ссылка на товар в магазине заказчика",
        ),
        sa.Column(
            "active_ingredients",
            sa.Text(),
            nullable=True,
            comment="Comma-separated active ingredients",
        ),
        sa.Column(
            "health_benefits",
            sa.Text(),
            nullable=True,
            comment="Comma-separated health benefits/tags",
        ),
        sa.Column(
            "target_biomarkers",
            sa.Text(),
            nullable=True,
            comment="Comma-separated biomarker codes this product helps with",
        ),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("reviews_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["product_categories.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_products_category_id"), "products", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_products_external_id"), "products", ["external_id"], unique=False
    )
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_index(op.f("ix_products_slug"), "products", ["slug"], unique=True)
    op.create_table(
        "analysis_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_files_analysis_id"),
        "analysis_files",
        ["analysis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_files_id"), "analysis_files", ["id"], unique=False
    )
    op.create_table(
        "user_biomarkers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("biomarker_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "LOW",
                "NORMAL",
                "HIGH",
                "CRITICAL_LOW",
                "CRITICAL_HIGH",
                name="biomarkerstatus",
            ),
            nullable=False,
        ),
        sa.Column("ref_min", sa.Float(), nullable=True),
        sa.Column("ref_max", sa.Float(), nullable=True),
        sa.Column(
            "raw_name",
            sa.String(length=255),
            nullable=True,
            comment="Original name from OCR",
        ),
        sa.Column(
            "raw_value",
            sa.String(length=100),
            nullable=True,
            comment="Original value string from OCR",
        ),
        sa.Column("measured_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["biomarker_id"], ["biomarkers.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_biomarkers_analysis_id"),
        "user_biomarkers",
        ["analysis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_biomarkers_biomarker_id"),
        "user_biomarkers",
        ["biomarker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_biomarkers_id"), "user_biomarkers", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_user_biomarkers_user_id"), "user_biomarkers", ["user_id"], unique=False
    )
    op.create_table(
        "product_recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_biomarker_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column(
            "reason",
            sa.Text(),
            nullable=False,
            comment="Why this product is recommended",
        ),
        sa.Column(
            "priority", sa.Integer(), nullable=False, comment="1 = highest priority"
        ),
        sa.Column(
            "confidence", sa.Float(), nullable=False, comment="AI confidence score 0-1"
        ),
        sa.Column(
            "is_dismissed",
            sa.Boolean(),
            nullable=False,
            comment="User dismissed this recommendation",
        ),
        sa.Column(
            "is_purchased",
            sa.Boolean(),
            nullable=False,
            comment="User purchased this product",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_biomarker_id"], ["user_biomarkers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_recommendations_id"),
        "product_recommendations",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_recommendations_product_id"),
        "product_recommendations",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_recommendations_user_biomarker_id"),
        "product_recommendations",
        ["user_biomarker_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_product_recommendations_user_biomarker_id"),
        table_name="product_recommendations",
    )
    op.drop_index(
        op.f("ix_product_recommendations_product_id"),
        table_name="product_recommendations",
    )
    op.drop_index(
        op.f("ix_product_recommendations_id"), table_name="product_recommendations"
    )
    op.drop_table("product_recommendations")
    op.drop_index(op.f("ix_user_biomarkers_user_id"), table_name="user_biomarkers")
    op.drop_index(op.f("ix_user_biomarkers_id"), table_name="user_biomarkers")
    op.drop_index(op.f("ix_user_biomarkers_biomarker_id"), table_name="user_biomarkers")
    op.drop_index(op.f("ix_user_biomarkers_analysis_id"), table_name="user_biomarkers")
    op.drop_table("user_biomarkers")
    op.drop_index(op.f("ix_analysis_files_id"), table_name="analysis_files")
    op.drop_index(op.f("ix_analysis_files_analysis_id"), table_name="analysis_files")
    op.drop_table("analysis_files")
    op.drop_index(op.f("ix_products_slug"), table_name="products")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_index(op.f("ix_products_external_id"), table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_medical_documents_id"), table_name="medical_documents")
    op.drop_table("medical_documents")
    op.drop_index(op.f("ix_health_reminders_user_id"), table_name="health_reminders")
    op.drop_index(
        op.f("ix_health_reminders_scheduled_date"), table_name="health_reminders"
    )
    op.drop_index(
        op.f("ix_health_reminders_next_occurrence"), table_name="health_reminders"
    )
    op.drop_index(op.f("ix_health_reminders_id"), table_name="health_reminders")
    op.drop_table("health_reminders")
    op.drop_index(op.f("ix_biomarker_references_id"), table_name="biomarker_references")
    op.drop_index(
        op.f("ix_biomarker_references_biomarker_id"), table_name="biomarker_references"
    )
    op.drop_table("biomarker_references")
    op.drop_index(op.f("ix_analyses_user_id"), table_name="analyses")
    op.drop_index(op.f("ix_analyses_id"), table_name="analyses")
    op.drop_table("analyses")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_external_user_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_product_categories_slug"), table_name="product_categories")
    op.drop_index(op.f("ix_product_categories_id"), table_name="product_categories")
    op.drop_table("product_categories")
    op.drop_index(op.f("ix_biomarkers_id"), table_name="biomarkers")
    op.drop_index(op.f("ix_biomarkers_code"), table_name="biomarkers")
    op.drop_table("biomarkers")
    # ### end Alembic commands ###
