"""init

Revision ID: 7f10c16ee5c1
Revises: 
Create Date: 2025-12-09 11:11:24.420833+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f10c16ee5c1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "biomarkers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "code",
            sa.String(length=50),
            nullable=False,
            comment="Unique code (e.g., HGB, FE, TSH)",
        ),
        sa.Column(
            "name_ru", sa.String(length=255), nullable=False, comment="Russian name"
        ),
        sa.Column(
            "name_en", sa.String(length=255), nullable=True, comment="English name"
        ),
        sa.Column(
            "aliases",
            sa.Text(),
            nullable=True,
            comment="Comma-separated aliases (HGB,Hb,Гемоглобин,Hemoglobin)",
        ),
        sa.Column(
            "category",
            sa.Enum(
                "HEMATOLOGY",
                "BIOCHEMISTRY",
                "HORMONES",
                "VITAMINS",
                "MINERALS",
                "LIPIDS",
                "LIVER",
                "KIDNEY",
                "THYROID",
                "INFLAMMATION",
                "OTHER",
                name="biomarkercategory",
            ),
            nullable=False,
        ),
        sa.Column(
            "default_unit",
            sa.String(length=50),
            nullable=False,
            comment="Default measurement unit",
        ),
        sa.Column(
            "alternative_units",
            sa.String(length=255),
            nullable=True,
            comment="Comma-separated alternative units with conversion factors",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="What this biomarker indicates",
        ),
        sa.Column(
            "low_recommendations",
            sa.Text(),
            nullable=True,
            comment="Recommendations when value is low",
        ),
        sa.Column(
            "high_recommendations",
            sa.Text(),
            nullable=True,
            comment="Recommendations when value is high",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("biomarkers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_biomarkers_code"), ["code"], unique=True)
        batch_op.create_index(batch_op.f("ix_biomarkers_id"), ["id"], unique=False)

    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("composition", sa.Text(), nullable=True),
        sa.Column("composition_table", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("sale_count", sa.Integer(), nullable=True),
        sa.Column("filter_stocks", sa.String(), nullable=True),
        sa.Column("value", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_products_external_id"), ["external_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_products_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_name"), ["name"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("birth_date", sa.DateTime(), nullable=True),
        sa.Column(
            "gender", sa.Enum("MALE", "FEMALE", "OTHER", name="gender"), nullable=True
        ),
        sa.Column(
            "external_user_id",
            sa.String(length=255),
            nullable=True,
            comment="ID пользователя во внешней системе заказчика",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_users_external_user_id"), ["external_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)

    op.create_table(
        "analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "title",
            sa.String(length=255),
            nullable=False,
            comment="User-friendly title",
        ),
        sa.Column(
            "analysis_type",
            sa.Enum(
                "BLOOD_GENERAL",
                "BLOOD_BIOCHEMISTRY",
                "HORMONES",
                "VITAMINS",
                "URINE",
                "OTHER",
                name="analysistype",
            ),
            nullable=False,
        ),
        sa.Column(
            "lab_provider",
            sa.Enum(
                "INVITRO",
                "KDL",
                "GEMOTEST",
                "HELIX",
                "CMD",
                "OTHER",
                name="labprovider",
            ),
            nullable=True,
        ),
        sa.Column(
            "lab_name",
            sa.String(length=255),
            nullable=True,
            comment="Custom lab name if not in enum",
        ),
        sa.Column(
            "analysis_date",
            sa.DateTime(),
            nullable=True,
            comment="Date when analysis was taken",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "MANUAL_REVIEW",
                name="analysisstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "error_message",
            sa.Text(),
            nullable=True,
            comment="Error details if processing failed",
        ),
        sa.Column("raw_text", sa.Text(), nullable=True, comment="Raw OCR text output"),
        sa.Column(
            "ai_summary",
            sa.Text(),
            nullable=True,
            comment="AI-generated summary of results",
        ),
        sa.Column(
            "ai_recommendations",
            sa.JSON(),
            nullable=True,
            comment="AI-generated recommendations",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("analyses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_analyses_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_analyses_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "biomarker_references",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("biomarker_id", sa.Integer(), nullable=False),
        sa.Column(
            "gender",
            sa.String(length=10),
            nullable=True,
            comment="male/female or null for both",
        ),
        sa.Column("age_min", sa.Integer(), nullable=True),
        sa.Column("age_max", sa.Integer(), nullable=True),
        sa.Column("ref_min", sa.Float(), nullable=True),
        sa.Column("ref_max", sa.Float(), nullable=True),
        sa.Column(
            "optimal_min",
            sa.Float(),
            nullable=True,
            comment="Optimal range lower bound",
        ),
        sa.Column(
            "optimal_max",
            sa.Float(),
            nullable=True,
            comment="Optimal range upper bound",
        ),
        sa.Column("critical_low", sa.Float(), nullable=True),
        sa.Column("critical_high", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["biomarker_id"], ["biomarkers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "biomarker_id",
            "gender",
            "age_min",
            "age_max",
            "unit",
            name="uq_biomarker_reference",
        ),
    )
    with op.batch_alter_table("biomarker_references", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_biomarker_references_biomarker_id"),
            ["biomarker_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_biomarker_references_id"), ["id"], unique=False
        )

    op.create_table(
        "health_reminders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "reminder_type",
            sa.Enum(
                "CHECKUP",
                "ANALYSIS",
                "SUPPLEMENT",
                "MEDICATION",
                "APPOINTMENT",
                "CUSTOM",
                name="remindertype",
            ),
            nullable=False,
        ),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("scheduled_time", sa.Time(), nullable=True),
        sa.Column(
            "frequency",
            sa.Enum(
                "ONCE",
                "DAILY",
                "WEEKLY",
                "MONTHLY",
                "QUARTERLY",
                "BIANNUALLY",
                "ANNUALLY",
                name="reminderfrequency",
            ),
            nullable=False,
        ),
        sa.Column("repeat_until", sa.Date(), nullable=True),
        sa.Column("last_triggered", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_occurrence", sa.Date(), nullable=True),
        sa.Column(
            "notify_days_before",
            sa.Integer(),
            nullable=False,
            comment="Send notification X days before",
        ),
        sa.Column("notify_on_day", sa.Boolean(), nullable=False),
        sa.Column("notification_sent", sa.Boolean(), nullable=False),
        sa.Column(
            "related_biomarkers",
            sa.String(length=500),
            nullable=True,
            comment="Comma-separated biomarker codes to check",
        ),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "external_calendar_id",
            sa.String(length=255),
            nullable=True,
            comment="ID in external calendar (Google, Apple)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("health_reminders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_health_reminders_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_health_reminders_next_occurrence"),
            ["next_occurrence"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_health_reminders_scheduled_date"),
            ["scheduled_date"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_health_reminders_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "medical_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "ANALYSIS",
                "CONSULTATION",
                "EXAMINATION",
                "OTHER",
                name="documentcategory",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", sa.String(length=500), nullable=True),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("visit_date", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("medical_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_medical_documents_id"), ["id"], unique=False
        )

    op.create_table(
        "patient_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "body_parameters", sa.JSON(), nullable=True, comment="Рост, вес, ИМТ и т.д."
        ),
        sa.Column(
            "gender_health",
            sa.JSON(),
            nullable=True,
            comment="Мужское/Женское здоровье",
        ),
        sa.Column(
            "medical_history", sa.JSON(), nullable=True, comment="История болезней"
        ),
        sa.Column(
            "allergies", sa.JSON(), nullable=True, comment="Аллергические реакции"
        ),
        sa.Column(
            "chronic_diseases",
            sa.JSON(),
            nullable=True,
            comment="Хронические заболевания",
        ),
        sa.Column(
            "hereditary_diseases",
            sa.JSON(),
            nullable=True,
            comment="Наследственные заболевания",
        ),
        sa.Column(
            "lifestyle",
            sa.JSON(),
            nullable=True,
            comment="Образ жизни (спорт, курение, диета)",
        ),
        sa.Column(
            "additional_info",
            sa.JSON(),
            nullable=True,
            comment="Дополнительная информация",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("patient_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_patient_profiles_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_patient_profiles_user_id"), ["user_id"], unique=True
        )

    op.create_table(
        "analysis_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("analysis_files", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analysis_files_analysis_id"), ["analysis_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_analysis_files_id"), ["id"], unique=False)

    op.create_table(
        "user_biomarkers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("biomarker_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "LOW",
                "NORMAL",
                "HIGH",
                "CRITICAL_LOW",
                "CRITICAL_HIGH",
                name="biomarkerstatus",
            ),
            nullable=False,
        ),
        sa.Column("ref_min", sa.Float(), nullable=True),
        sa.Column("ref_max", sa.Float(), nullable=True),
        sa.Column(
            "raw_name",
            sa.String(length=255),
            nullable=True,
            comment="Original name from OCR",
        ),
        sa.Column(
            "raw_value",
            sa.String(length=100),
            nullable=True,
            comment="Original value string from OCR",
        ),
        sa.Column("measured_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["biomarker_id"], ["biomarkers.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_biomarkers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_biomarkers_analysis_id"), ["analysis_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_biomarkers_biomarker_id"),
            ["biomarker_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_user_biomarkers_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_user_biomarkers_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_biomarkers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_biomarkers_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_biomarkers_id"))
        batch_op.drop_index(batch_op.f("ix_user_biomarkers_biomarker_id"))
        batch_op.drop_index(batch_op.f("ix_user_biomarkers_analysis_id"))

    op.drop_table("user_biomarkers")
    with op.batch_alter_table("analysis_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_files_id"))
        batch_op.drop_index(batch_op.f("ix_analysis_files_analysis_id"))

    op.drop_table("analysis_files")
    with op.batch_alter_table("patient_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_patient_profiles_user_id"))
        batch_op.drop_index(batch_op.f("ix_patient_profiles_id"))

    op.drop_table("patient_profiles")
    with op.batch_alter_table("medical_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_medical_documents_id"))

    op.drop_table("medical_documents")
    with op.batch_alter_table("health_reminders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_health_reminders_user_id"))
        batch_op.drop_index(batch_op.f("ix_health_reminders_scheduled_date"))
        batch_op.drop_index(batch_op.f("ix_health_reminders_next_occurrence"))
        batch_op.drop_index(batch_op.f("ix_health_reminders_id"))

    op.drop_table("health_reminders")
    with op.batch_alter_table("biomarker_references", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_biomarker_references_id"))
        batch_op.drop_index(batch_op.f("ix_biomarker_references_biomarker_id"))

    op.drop_table("biomarker_references")
    with op.batch_alter_table("analyses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analyses_user_id"))
        batch_op.drop_index(batch_op.f("ix_analyses_id"))

    op.drop_table("analyses")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_id"))
        batch_op.drop_index(batch_op.f("ix_users_external_user_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_products_name"))
        batch_op.drop_index(batch_op.f("ix_products_id"))
        batch_op.drop_index(batch_op.f("ix_products_external_id"))

    op.drop_table("products")
    with op.batch_alter_table("biomarkers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_biomarkers_id"))
        batch_op.drop_index(batch_op.f("ix_biomarkers_code"))

    op.drop_table("biomarkers")
    # ### end Alembic commands ###
